data_path: ../data/Bar_perm_5000_100425/config.yaml
train_method: self-supervised
img_size: 140
crop_size: 60
num_channels: 20
learning_rate: 0.0003
batch_size: 32
weight_decay: 0.004
momentum: 0.996
n_epochs: 40
device: cuda:0