api {
  web_server: https://app.ml.physgenai.appliedai.tech
  api_server: https://api.ml.physgenai.appliedai.tech
  files_server: https://files.ml.physgenai.appliedai.tech
  
  credentials {
    "access_key" = "FLTZ2YX8NOYPDDVM02SAD7YU3MC7OJ"
    "secret_key" = "1Vp_EAqcwlujCGBgzcmjfdR63DRmZK7ZEr3zeCQK91Lcov_cGhcMqObG85hxqazSLF8"
  }
}
